baseURL = "https://blog.clubelec.insset.fr"
languageCode = "fr-FR"
title = "le blog du club elec"
theme = "clubelecblog"
dateFormat = "2 Jan 2006"
dateFormatFull = "02/01/2006"
dateFormatTime = "2 Jan 2006 15:04"

[permalinks]
  posts = '/:year/:month/:day/:title/'

[author]
  name = "club elec"
  homepage = "https://clubelec.insset.fr/"
